#!/usr/bin/env python3
"""Divergence-free E-019 tensor source and retarded weak-gravity solver.

The model uses a compact one-dimensional line source embedded in 3+1
dimensional flat spacetime.  Its harmonic amplitudes contain T^{00}, T^{0x},
and T^{xx} and satisfy partial_mu T^{mu nu}=0 by construction.  A retarded
Green-function solver then computes the trace-reversed metric, checks harmonic
gauge, and evaluates the gauge-invariant R_{0x0x} tidal component.
"""

from __future__ import annotations

import argparse
import cmath
import json
import math
from dataclasses import dataclass, field
from typing import Protocol, Sequence

if __package__:
    from .e019_conserved_cavity import C, G
else:
    from e019_conserved_cavity import C, G


ComplexTriple = tuple[complex, complex, complex]
HBAR = 1.054_571_817e-34


def complex_fsum(values: Sequence[complex]) -> complex:
    return complex(
        math.fsum(value.real for value in values),
        math.fsum(value.imag for value in values),
    )


def complex_summary(value: complex) -> dict[str, float]:
    return {
        "real": value.real,
        "imag": value.imag,
        "magnitude": abs(value),
        "phase_deg": math.degrees(cmath.phase(value)),
    }


class HarmonicLineTensor(Protocol):
    energy_j: float
    length_m: float
    frequency_hz: float
    grid_cells: int

    @property
    def omega(self) -> float: ...

    @property
    def wave_number(self) -> float: ...

    def grid(self) -> tuple[tuple[float, ...], float]: ...

    def amplitudes(self, x_m: float) -> ComplexTriple: ...


@dataclass(frozen=True)
class ConservedCavityTensor:
    """Compact total-apparatus perturbation generated by a superpotential.

    With harmonic convention Re[A exp(-i omega t)], define a compact spatial
    potential P(x).  The line-integrated tensor amplitudes are

      tau00 = P''
      tau0x = i (omega/c) P'
      tauxx = -(omega/c)^2 P.

    The two nontrivial conservation equations then vanish identically.  P is
    chosen so P, P', and P'' vanish at the cavity boundaries.  Its central
    positive tau00 region represents field energy while the negative outer
    perturbation represents energy removed from the rest of the apparatus.
    """

    energy_j: float = 1.0
    length_m: float = 0.01
    frequency_hz: float = 100e6
    grid_cells: int = 2001
    _potential_scale_j_m: float = field(init=False, repr=False)

    def __post_init__(self) -> None:
        if self.energy_j <= 0:
            raise ValueError("energy must be positive")
        if self.length_m <= 0:
            raise ValueError("length must be positive")
        if self.frequency_hz <= 0:
            raise ValueError("frequency must be positive")
        if self.grid_cells < 101 or self.grid_cells % 2 == 0:
            raise ValueError("grid_cells must be an odd integer of at least 101")

        points, dx = self.grid()
        raw_positive = math.fsum(
            max(self._raw_potential_terms(x_m)[2], 0.0) * dx for x_m in points
        )
        if raw_positive <= 0:
            raise ValueError("source profile has no positive energy region")
        object.__setattr__(
            self, "_potential_scale_j_m", self.energy_j / raw_positive
        )

    @property
    def omega(self) -> float:
        return 2.0 * math.pi * self.frequency_hz

    @property
    def wave_number(self) -> float:
        return self.omega / C

    @property
    def retardation_parameter(self) -> float:
        return self.omega * self.length_m / C

    def grid(self) -> tuple[tuple[float, ...], float]:
        dx = self.length_m / self.grid_cells
        left = -self.length_m / 2.0
        points = tuple(left + (index + 0.5) * dx for index in range(self.grid_cells))
        return points, dx

    def _shape(self, x_m: float) -> tuple[float, float, float]:
        scaled_x = 2.0 * x_m / self.length_m
        if abs(scaled_x) >= 1.0:
            return 0.0, 0.0, 0.0
        one_minus = 1.0 - scaled_x**2
        shape = one_minus**4
        first = -8.0 * scaled_x * one_minus**3
        second = 8.0 * one_minus**2 * (7.0 * scaled_x**2 - 1.0)
        return shape, first, second

    def _raw_potential_terms(self, x_m: float) -> tuple[float, float, float]:
        shape, first, second = self._shape(x_m)
        # The minus sign makes the central T00 perturbation positive.
        potential = -shape
        first_x = -(2.0 / self.length_m) * first
        second_x = -(4.0 / self.length_m**2) * second
        return potential, first_x, second_x

    def potential_terms(self, x_m: float) -> tuple[float, float, float]:
        return tuple(
            self._potential_scale_j_m * value
            for value in self._raw_potential_terms(x_m)
        )

    def amplitudes(self, x_m: float) -> ComplexTriple:
        potential, first_x, second_x = self.potential_terms(x_m)
        omega_over_c = self.omega / C
        return (
            complex(second_x, 0.0),
            1j * omega_over_c * first_x,
            complex(-(omega_over_c**2) * potential, 0.0),
        )

    def integrated_component(self, component: int) -> complex:
        points, dx = self.grid()
        return complex_fsum(
            tuple(self.amplitudes(x_m)[component] * dx for x_m in points)
        )

    def energy_ledger(self) -> dict[str, float]:
        points, dx = self.grid()
        densities = tuple(self.amplitudes(x_m)[0].real for x_m in points)
        positive = math.fsum(max(value, 0.0) * dx for value in densities)
        negative = math.fsum(min(value, 0.0) * dx for value in densities)
        return {
            "positive_field_region_J": positive,
            "negative_apparatus_region_J": negative,
            "net_J": positive + negative,
        }

    def energy_moment(self, order: int) -> complex:
        if order < 0:
            raise ValueError("moment order must be non-negative")
        points, dx = self.grid()
        return complex_fsum(
            tuple(
                self.amplitudes(x_m)[0] * x_m**order * dx for x_m in points
            )
        )

    def absolute_component_budget(self) -> dict[str, float]:
        points, dx = self.grid()
        integrated = []
        for component in range(3):
            integrated.append(
                math.fsum(
                    abs(self.amplitudes(x_m)[component]) * dx for x_m in points
                )
            )
        return {
            "integral_abs_T00_J": integrated[0],
            "integral_abs_T0x_J": integrated[1],
            "integral_abs_Txx_J": integrated[2],
            "abs_T0x_to_positive_energy": integrated[1] / self.energy_j,
            "abs_Txx_to_positive_energy": integrated[2] / self.energy_j,
        }

    def source_conservation_residual(self, samples: int = 41) -> dict[str, float]:
        """Numerically differentiate the source away from compact boundaries."""

        step = self.length_m * 1e-5
        max_energy_residual = 0.0
        max_momentum_residual = 0.0
        max_energy_scale = 0.0
        max_momentum_scale = 0.0
        for index in range(samples):
            x_m = self.length_m * (-0.45 + 0.9 * index / (samples - 1))
            center = self.amplitudes(x_m)
            left = self.amplitudes(x_m - step)
            right = self.amplitudes(x_m + step)
            d_t0x_dx = (right[1] - left[1]) / (2.0 * step)
            d_txx_dx = (right[2] - left[2]) / (2.0 * step)
            energy_time = -1j * self.omega / C * center[0]
            momentum_time = -1j * self.omega / C * center[1]
            energy_residual = energy_time + d_t0x_dx
            momentum_residual = momentum_time + d_txx_dx
            energy_scale = abs(energy_time) + abs(d_t0x_dx)
            momentum_scale = abs(momentum_time) + abs(d_txx_dx)
            max_energy_residual = max(max_energy_residual, abs(energy_residual))
            max_momentum_residual = max(
                max_momentum_residual, abs(momentum_residual)
            )
            max_energy_scale = max(max_energy_scale, energy_scale)
            max_momentum_scale = max(max_momentum_scale, momentum_scale)
        return {
            "energy_equation_relative": (
                max_energy_residual / max_energy_scale if max_energy_scale else 0.0
            ),
            "momentum_equation_relative": (
                max_momentum_residual / max_momentum_scale
                if max_momentum_scale
                else 0.0
            ),
        }


@dataclass(frozen=True)
class IncompleteFieldOnlyTensor:
    """Intentionally nonconserved comparison that keeps only positive T00."""

    reference: ConservedCavityTensor

    @property
    def energy_j(self) -> float:
        return self.reference.energy_j

    @property
    def length_m(self) -> float:
        return self.reference.length_m

    @property
    def frequency_hz(self) -> float:
        return self.reference.frequency_hz

    @property
    def grid_cells(self) -> int:
        return self.reference.grid_cells

    @property
    def omega(self) -> float:
        return self.reference.omega

    @property
    def wave_number(self) -> float:
        return self.reference.wave_number

    def grid(self) -> tuple[tuple[float, ...], float]:
        return self.reference.grid()

    def amplitudes(self, x_m: float) -> ComplexTriple:
        energy_density = max(self.reference.amplitudes(x_m)[0].real, 0.0)
        return complex(energy_density, 0.0), 0j, 0j


@dataclass(frozen=True)
class RetardedLineMetric:
    source: HarmonicLineTensor

    def _validate_probe(self, probe_x_m: float, probe_rho_m: float) -> None:
        if probe_rho_m < 0:
            raise ValueError("probe_rho_m must be non-negative")
        if (
            probe_rho_m == 0.0
            and abs(probe_x_m) <= self.source.length_m / 2.0
        ):
            raise ValueError("on-axis probe must lie outside the compact source")

    def _bar_h_upper_kernel_derivative(
        self,
        probe_x_m: float,
        probe_rho_m: float,
        derivative_order: int,
    ) -> ComplexTriple:
        self._validate_probe(probe_x_m, probe_rho_m)
        if derivative_order not in (0, 1, 2):
            raise ValueError("kernel derivative order must be 0, 1, or 2")
        points, dx = self.source.grid()
        component_terms: tuple[list[complex], list[complex], list[complex]] = (
            [],
            [],
            [],
        )
        for source_x_m in points:
            delta_x = probe_x_m - source_x_m
            distance = math.hypot(delta_x, probe_rho_m)
            if distance == 0.0:
                raise ValueError("probe coincides with source cell")
            phase = cmath.exp(1j * self.source.wave_number * distance)
            wave_number = self.source.wave_number
            kernel = phase / distance
            if derivative_order == 0:
                retarded_kernel = kernel
            else:
                kernel_r = phase * (
                    1j * wave_number / distance - 1.0 / distance**2
                )
                if derivative_order == 1:
                    retarded_kernel = kernel_r * delta_x / distance
                else:
                    kernel_rr = phase * (
                        -(wave_number**2) / distance
                        - 2j * wave_number / distance**2
                        + 2.0 / distance**3
                    )
                    retarded_kernel = (
                        kernel_rr * delta_x**2 / distance**2
                        + kernel_r * probe_rho_m**2 / distance**3
                    )
            amplitudes = self.source.amplitudes(source_x_m)
            for component in range(3):
                component_terms[component].append(
                    amplitudes[component] * retarded_kernel * dx
                )
        factor = 4.0 * G / C**4
        return tuple(
            factor * complex_fsum(tuple(terms)) for terms in component_terms
        )

    def bar_h_upper_amplitude(
        self, probe_x_m: float, probe_rho_m: float = 0.0
    ) -> ComplexTriple:
        return self._bar_h_upper_kernel_derivative(
            probe_x_m, probe_rho_m, derivative_order=0
        )

    @staticmethod
    def _lower_metric_from_bar(bar_upper: ComplexTriple) -> ComplexTriple:
        bar_00_upper, bar_0x_upper, bar_xx_upper = bar_upper
        bar_00_lower = bar_00_upper
        bar_0x_lower = -bar_0x_upper
        bar_xx_lower = bar_xx_upper
        bar_trace = -bar_00_lower + bar_xx_lower
        h_00 = bar_00_lower + 0.5 * bar_trace
        h_0x = bar_0x_lower
        h_xx = bar_xx_lower - 0.5 * bar_trace
        return h_00, h_0x, h_xx

    def metric_lower_amplitude(
        self, probe_x_m: float, probe_rho_m: float = 0.0
    ) -> ComplexTriple:
        return self._lower_metric_from_bar(
            self.bar_h_upper_amplitude(probe_x_m, probe_rho_m)
        )

    def harmonic_gauge_residual(
        self,
        probe_x_m: float,
        probe_rho_m: float = 0.0,
    ) -> dict[str, object]:
        center = self.bar_h_upper_amplitude(probe_x_m, probe_rho_m)
        first_x = self._bar_h_upper_kernel_derivative(
            probe_x_m, probe_rho_m, derivative_order=1
        )
        d_bar_0x_dx = first_x[1]
        d_bar_xx_dx = first_x[2]
        time_00 = -1j * self.source.omega / C * center[0]
        time_0x = -1j * self.source.omega / C * center[1]
        residual_0 = time_00 + d_bar_0x_dx
        residual_x = time_0x + d_bar_xx_dx
        scale_0 = abs(time_00) + abs(d_bar_0x_dx)
        scale_x = abs(time_0x) + abs(d_bar_xx_dx)
        return {
            "nu_0": complex_summary(residual_0),
            "nu_x": complex_summary(residual_x),
            "nu_0_relative": abs(residual_0) / scale_0 if scale_0 else 0.0,
            "nu_x_relative": abs(residual_x) / scale_x if scale_x else 0.0,
            "derivative_method": "analytic retarded-kernel derivative",
        }

    def tidal_amplitude(
        self,
        probe_x_m: float,
        probe_rho_m: float = 0.0,
    ) -> dict[str, complex | float]:
        """Return R_0x0x and -c^2 R_0x0x harmonic amplitudes."""

        center = self.metric_lower_amplitude(probe_x_m, probe_rho_m)
        first_x = self._lower_metric_from_bar(
            self._bar_h_upper_kernel_derivative(
                probe_x_m, probe_rho_m, derivative_order=1
            )
        )
        second_x = self._lower_metric_from_bar(
            self._bar_h_upper_kernel_derivative(
                probe_x_m, probe_rho_m, derivative_order=2
            )
        )
        d_h0x_dx = first_x[1]
        d2_h00_dx2 = second_x[0]
        r_0x0x = (
            -1j * self.source.omega / C * d_h0x_dx
            - 0.5
            * (d2_h00_dx2 - (self.source.omega / C) ** 2 * center[2])
        )
        tidal_gradient = -C**2 * r_0x0x
        return {
            "R_0x0x_per_m2": r_0x0x,
            "tidal_gradient_per_s2": tidal_gradient,
            "derivative_method": "analytic retarded-kernel derivative",
        }

    def instantaneous_scalar_acceleration(
        self, probe_x_m: float, probe_rho_m: float = 0.0
    ) -> complex:
        """Newtonian T00-only amplitude, used only as a low-frequency check."""

        self._validate_probe(probe_x_m, probe_rho_m)
        points, dx = self.source.grid()
        terms: list[complex] = []
        for source_x_m in points:
            delta_x = probe_x_m - source_x_m
            distance = math.hypot(delta_x, probe_rho_m)
            tau_00 = self.source.amplitudes(source_x_m)[0]
            terms.append(-G / C**2 * tau_00 * delta_x / distance**3 * dx)
        return complex_fsum(tuple(terms))

    def instantaneous_scalar_tidal_gradient(
        self,
        probe_x_m: float,
        probe_rho_m: float = 0.0,
    ) -> complex:
        self._validate_probe(probe_x_m, probe_rho_m)
        points, dx = self.source.grid()
        terms: list[complex] = []
        for source_x_m in points:
            delta_x = probe_x_m - source_x_m
            distance = math.hypot(delta_x, probe_rho_m)
            tau_00 = self.source.amplitudes(source_x_m)[0]
            kernel_derivative = 1.0 / distance**3 - 3.0 * delta_x**2 / distance**5
            terms.append(-G / C**2 * tau_00 * kernel_derivative * dx)
        return complex_fsum(tuple(terms))


def tensor_result(
    source: HarmonicLineTensor,
    probe_x_m: float,
    probe_rho_m: float,
    baseline_m: float,
) -> dict[str, object]:
    solver = RetardedLineMetric(source)
    bar_h = solver.bar_h_upper_amplitude(probe_x_m, probe_rho_m)
    metric = solver.metric_lower_amplitude(probe_x_m, probe_rho_m)
    gauge = solver.harmonic_gauge_residual(probe_x_m, probe_rho_m)
    tidal = solver.tidal_amplitude(probe_x_m, probe_rho_m)
    r_0x0x = tidal["R_0x0x_per_m2"]
    gradient = tidal["tidal_gradient_per_s2"]
    assert isinstance(r_0x0x, complex)
    assert isinstance(gradient, complex)
    return {
        "bar_h_upper": {
            "00": complex_summary(bar_h[0]),
            "0x": complex_summary(bar_h[1]),
            "xx": complex_summary(bar_h[2]),
        },
        "h_lower": {
            "00": complex_summary(metric[0]),
            "0x": complex_summary(metric[1]),
            "xx": complex_summary(metric[2]),
        },
        "harmonic_gauge": gauge,
        "R_0x0x_per_m2": complex_summary(r_0x0x),
        "tidal_gradient_per_s2": complex_summary(gradient),
        "relative_acceleration_over_baseline_m_s2": abs(gradient) * baseline_m,
    }


def stochastic_noise_projection(
    *,
    modulation_frequency_hz: float,
    optical_wavelength_m: float,
    mean_photons: float,
    kappa_hz: float,
    tidal_transfer_per_j: float,
    baseline_m: float,
) -> dict[str, object]:
    """Project the E-018 exponential noise model through the E-019 transfer.

    For C_E(t)=(hbar omega_opt)^2 Var(n) exp(-kappa |t|), the two-sided
    per-Hz PSD evaluated at f is

      S_E(f)=2 (hbar omega_opt)^2 Var(n) kappa /
             (kappa^2 + (2 pi f)^2),

    with kappa expressed in radians per second.  The one-sided positive-
    frequency PSD is twice this value.
    """

    if optical_wavelength_m <= 0:
        raise ValueError("optical wavelength must be positive")
    if mean_photons < 0:
        raise ValueError("mean photons must be non-negative")
    if kappa_hz <= 0:
        raise ValueError("kappa_hz must be positive")
    optical_omega = 2.0 * math.pi * C / optical_wavelength_m
    photon_energy = HBAR * optical_omega
    analysis_omega = 2.0 * math.pi * modulation_frequency_hz
    kappa = 2.0 * math.pi * kappa_hz
    variances = {
        "coherent": mean_photons,
        "squeezed_vacuum": 2.0 * mean_photons * (mean_photons + 1.0),
    }
    states: dict[str, dict[str, float]] = {}
    for name, variance in variances.items():
        two_sided_psd = (
            2.0
            * photon_energy**2
            * variance
            * kappa
            / (kappa**2 + analysis_omega**2)
        )
        one_sided_energy_asd = math.sqrt(2.0 * two_sided_psd)
        tidal_asd = tidal_transfer_per_j * one_sided_energy_asd
        states[name] = {
            "photon_number_variance": variance,
            "energy_PSD_two_sided_J2_per_Hz": two_sided_psd,
            "energy_ASD_one_sided_J_per_sqrt_Hz": one_sided_energy_asd,
            "tidal_ASD_one_sided_per_s2_sqrt_Hz": tidal_asd,
            "relative_acceleration_ASD_one_sided_m_s2_sqrt_Hz": (
                tidal_asd * baseline_m
            ),
        }
    coherent_asd = states["coherent"][
        "relative_acceleration_ASD_one_sided_m_s2_sqrt_Hz"
    ]
    squeezed_asd = states["squeezed_vacuum"][
        "relative_acceleration_ASD_one_sided_m_s2_sqrt_Hz"
    ]
    return {
        "optical_wavelength_m": optical_wavelength_m,
        "optical_photon_energy_J": photon_energy,
        "mean_photons": mean_photons,
        "kappa_Hz": kappa_hz,
        "analysis_frequency_Hz": modulation_frequency_hz,
        "tidal_transfer_per_s2_per_J": tidal_transfer_per_j,
        "states": states,
        "squeezed_to_coherent_ASD_ratio": (
            squeezed_asd / coherent_asd if coherent_asd else None
        ),
    }


def build_report(args: argparse.Namespace) -> dict[str, object]:
    source = ConservedCavityTensor(
        energy_j=args.energy_j,
        length_m=args.length_m,
        frequency_hz=args.frequency_hz,
        grid_cells=args.grid_cells,
    )
    invalid_source = IncompleteFieldOnlyTensor(source)
    solver = RetardedLineMetric(source)
    scalar_tidal = solver.instantaneous_scalar_tidal_gradient(
        args.probe_x_m, args.probe_rho_m
    )
    conserved_result = tensor_result(
        source,
        args.probe_x_m,
        args.probe_rho_m,
        args.baseline_m,
    )
    gradient_magnitude = conserved_result["tidal_gradient_per_s2"]["magnitude"]
    assert isinstance(gradient_magnitude, float)
    tidal_transfer_per_j = gradient_magnitude / source.energy_j
    stochastic_projection = stochastic_noise_projection(
        modulation_frequency_hz=source.frequency_hz,
        optical_wavelength_m=args.optical_wavelength_m,
        mean_photons=args.mean_photons,
        kappa_hz=args.kappa_hz,
        tidal_transfer_per_j=tidal_transfer_per_j,
        baseline_m=args.baseline_m,
    )

    sweep: list[dict[str, float]] = []
    for factor in (0.01, 1.0, 100.0):
        frequency = args.frequency_hz * factor
        sweep_source = ConservedCavityTensor(
            energy_j=args.energy_j,
            length_m=args.length_m,
            frequency_hz=frequency,
            grid_cells=args.grid_cells,
        )
        sweep_solver = RetardedLineMetric(sweep_source)
        sweep_tidal = sweep_solver.tidal_amplitude(
            args.probe_x_m, args.probe_rho_m
        )["tidal_gradient_per_s2"]
        assert isinstance(sweep_tidal, complex)
        sweep_gauge = sweep_solver.harmonic_gauge_residual(
            args.probe_x_m, args.probe_rho_m
        )
        sweep_budget = sweep_source.absolute_component_budget()
        sweep.append(
            {
                "frequency_hz": frequency,
                "omega_L_over_c": sweep_source.retardation_parameter,
                "tidal_gradient_magnitude_per_s2": abs(sweep_tidal),
                "gauge_nu_0_relative": float(sweep_gauge["nu_0_relative"]),
                "gauge_nu_x_relative": float(sweep_gauge["nu_x_relative"]),
                "abs_T0x_to_positive_energy": sweep_budget[
                    "abs_T0x_to_positive_energy"
                ],
                "abs_Txx_to_positive_energy": sweep_budget[
                    "abs_Txx_to_positive_energy"
                ],
            }
        )

    return {
        "model": "E-019 divergence-free line tensor and retarded tidal solver",
        "parameters": {
            "energy_J": args.energy_j,
            "length_m": args.length_m,
            "frequency_Hz": args.frequency_hz,
            "omega_L_over_c": source.retardation_parameter,
            "probe_x_m": args.probe_x_m,
            "probe_rho_m": args.probe_rho_m,
            "baseline_m": args.baseline_m,
            "grid_cells": args.grid_cells,
        },
        "source": {
            "construction": (
                "tau00=P'', tau0x=i(omega/c)P', tauxx=-(omega/c)^2P"
            ),
            "energy_ledger": source.energy_ledger(),
            "moments": {
                "I0_J": complex_summary(source.energy_moment(0)),
                "I1_J_m": complex_summary(source.energy_moment(1)),
                "I2_J_m2": complex_summary(source.energy_moment(2)),
            },
            "integrated_T0x_J": complex_summary(source.integrated_component(1)),
            "integrated_Txx_J": complex_summary(source.integrated_component(2)),
            "conservation_residual": source.source_conservation_residual(),
            "absolute_component_budget": source.absolute_component_budget(),
        },
        "conserved_retarded_solution": conserved_result,
        "static_T00_tidal_benchmark_per_s2": complex_summary(scalar_tidal),
        "retarded_to_static_tidal_ratio": (
            gradient_magnitude / abs(scalar_tidal) if scalar_tidal != 0 else None
        ),
        "stochastic_noise_projection": stochastic_projection,
        "invalid_field_only_comparison": {
            "warning": (
                "This comparison changes total energy without flux or stress and "
                "therefore does not define a consistent linearized-GR source."
            ),
            "retarded_solution": tensor_result(
                invalid_source,
                args.probe_x_m,
                args.probe_rho_m,
                args.baseline_m,
            ),
        },
        "frequency_sweep": sweep,
        "stopping_rule": (
            "The deterministic transfer survives and is gauge-consistent, so the "
            "E-018 noise model has been projected through it. Stop before a more "
            "detailed quantum treatment unless an explicit mirror/pump/absorber "
            "decomposition changes the transfer by orders of magnitude."
        ),
    }


def render_text(report: dict[str, object]) -> str:
    parameters = report["parameters"]
    source = report["source"]
    solution = report["conserved_retarded_solution"]
    invalid = report["invalid_field_only_comparison"]
    assert isinstance(parameters, dict)
    assert isinstance(source, dict)
    assert isinstance(solution, dict)
    assert isinstance(invalid, dict)
    ledger = source["energy_ledger"]
    moments = source["moments"]
    conservation = source["conservation_residual"]
    gauge = solution["harmonic_gauge"]
    tidal = solution["tidal_gradient_per_s2"]
    invalid_solution = invalid["retarded_solution"]
    invalid_gauge = invalid_solution["harmonic_gauge"]
    assert isinstance(ledger, dict)
    assert isinstance(moments, dict)
    assert isinstance(conservation, dict)
    assert isinstance(gauge, dict)
    assert isinstance(tidal, dict)
    assert isinstance(invalid_solution, dict)
    assert isinstance(invalid_gauge, dict)
    noise = report["stochastic_noise_projection"]
    assert isinstance(noise, dict)
    noise_states = noise["states"]
    assert isinstance(noise_states, dict)
    coherent_noise = noise_states["coherent"]
    squeezed_noise = noise_states["squeezed_vacuum"]

    lines = [
        str(report["model"]),
        (
            f"E={parameters['energy_J']:.6g} J, L={parameters['length_m']:.6g} m, "
            f"f={parameters['frequency_Hz']:.6g} Hz, omega L/c="
            f"{parameters['omega_L_over_c']:.6e}"
        ),
        "",
        "Conserved source ledger:",
        (
            f"  positive={ledger['positive_field_region_J']:.6e} J  "
            f"negative={ledger['negative_apparatus_region_J']:.6e} J  "
            f"net={ledger['net_J']:.3e} J"
        ),
        (
            f"  |I0|={moments['I0_J']['magnitude']:.3e} J  "
            f"|I1|={moments['I1_J_m']['magnitude']:.3e} J m  "
            f"I2={moments['I2_J_m2']['real']:.6e} J m^2"
        ),
        (
            f"  source residuals: energy={conservation['energy_equation_relative']:.3e}  "
            f"momentum={conservation['momentum_equation_relative']:.3e}"
        ),
        "",
        "Retarded exterior result:",
        (
            f"  harmonic gauge residuals: nu=0 {gauge['nu_0_relative']:.3e}, "
            f"nu=x {gauge['nu_x_relative']:.3e}"
        ),
        (
            f"  |tidal gradient|={tidal['magnitude']:.6e} s^-2  "
            f"relative acceleration over {parameters['baseline_m']:.6g} m="
            f"{solution['relative_acceleration_over_baseline_m_s2']:.6e} m/s^2"
        ),
        (
            f"  retarded/static-T00 tidal ratio="
            f"{report['retarded_to_static_tidal_ratio']:.6e}"
        ),
        "",
        "Stochastic projection:",
        (
            f"  coherent relative-acceleration ASD="
            f"{coherent_noise['relative_acceleration_ASD_one_sided_m_s2_sqrt_Hz']:.6e} "
            "m/s^2/sqrt(Hz)"
        ),
        (
            f"  squeezed relative-acceleration ASD="
            f"{squeezed_noise['relative_acceleration_ASD_one_sided_m_s2_sqrt_Hz']:.6e} "
            f"m/s^2/sqrt(Hz)  ratio={noise['squeezed_to_coherent_ASD_ratio']:.6g}"
        ),
        "",
        "Invalid field-only comparison:",
        (
            f"  harmonic gauge residuals: nu=0 {invalid_gauge['nu_0_relative']:.3e}, "
            f"nu=x {invalid_gauge['nu_x_relative']:.3e}"
        ),
        "",
        "Frequency sweep:",
    ]
    sweep = report["frequency_sweep"]
    assert isinstance(sweep, list)
    for row in sweep:
        lines.append(
            f"  f={row['frequency_hz']:.6e} Hz  omegaL/c={row['omega_L_over_c']:.3e}  "
            f"|K|={row['tidal_gradient_magnitude_per_s2']:.6e} s^-2  "
            f"|Txx|/E={row['abs_Txx_to_positive_energy']:.3e}  "
            f"gauge=({row['gauge_nu_0_relative']:.2e}, "
            f"{row['gauge_nu_x_relative']:.2e})"
        )
    lines.extend(["", str(report["stopping_rule"])])
    return "\n".join(lines)


def parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--energy-j", type=float, default=1.0)
    parser.add_argument("--length-m", type=float, default=0.01)
    parser.add_argument("--frequency-hz", type=float, default=100e6)
    parser.add_argument("--probe-x-m", type=float, default=1.0)
    parser.add_argument("--probe-rho-m", type=float, default=0.0)
    parser.add_argument("--baseline-m", type=float, default=1.0)
    parser.add_argument("--grid-cells", type=int, default=2001)
    parser.add_argument("--optical-wavelength-m", type=float, default=1.55e-6)
    parser.add_argument("--mean-photons", type=float, default=4.5)
    parser.add_argument("--kappa-hz", type=float, default=100e6)
    parser.add_argument("--json", action="store_true", dest="as_json")
    return parser.parse_args(argv)


def main(argv: Sequence[str] | None = None) -> int:
    args = parse_args(argv)
    report = build_report(args)
    if args.as_json:
        print(json.dumps(report, indent=2, sort_keys=True, allow_nan=False))
    else:
        print(render_text(report))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
